### PR TITLE
add ReLU in Header Conv

### PR DESCRIPTION
**Pull request by developer0hye**
add ReLU in Header Conv

image

Original implementation includes ReLU() in Header.

In my experiments, It reported 75.73 mAP.

Your pre-trained model was trained without ReLU. If you want pretrained model with ReLU, I can share it for you.

### CODE REVIEW

**Comment by yjh0410** [comment]
I use leakyReLU in my head conv, and you add a ReLU following my Conv.


LeakyReLU + ReLU = ReLU.


So maybe ReLU is a better choice in CenterNet.


Thanks for your advice. I will try again with ReLU instead of LeakyReLU.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjh0410/CenterNet-Lite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 上午9:29
收件人:&nbsp;"yjh0410/CenterNet-Lite"<CenterNet-Lite@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yjh0410/CenterNet-Lite] add ReLU in Header Conv (#11)




add ReLU in Header Conv
 

 
Original implementation includes ReLU() in Header.
 
In my experiments, It reported 75.73 mAP.
 
Your pre-trained model was trained without ReLU. If you want pretrained model with ReLU, I can share it for you.
 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/yjh0410/CenterNet-Lite/pull/11
 
Commit Summary
    
add ReLU in Header Conv
  
File Changes
    
     M     models/centernet.py     (5)   
  
Patch Links:
    
https://github.com/yjh0410/CenterNet-Lite/pull/11.patch
   
https://github.com/yjh0410/CenterNet-Lite/pull/11.diff

**Comment by developer0hye** [comment]
@yjh0410 

I changed leaky relu(from deconv) -> conv 3x3 -> conv 1x1 to leaky relu(from deconv) -> conv 3x3 -> relu -> conv 1x1.

So, It's not leaky->relu = relu!

**Comment by developer0hye** [comment]
I trained the model setting batchsize to 16.

**Comment by developer0hye** [comment]
Ah.... I understood your answer. I thought `Conv` has not activation function.

**Pull request closed without merging**
