### PR TITLE
 Fix 'Namespace' object has no attribute 'num_classes'

### PR DESCRIPTION
**Pull request by developer0hye**
Fix 'Namespace' object has no attribute 'num_classes'

Hi, yjh!

I found grammatical error in your code and then fixed it!

### CODE REVIEW

**Comment by developer0hye** [comment]
@yjh0410 Are you busy recently?

**Comment by yjh0410** [comment]
Sorry for my fault.


I returned my school recently and there are many trouble things to address. I merge your request just now.&nbsp;


Thank you very much for your reminder and help !!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjh0410/CenterNet-Lite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 晚上9:38
收件人:&nbsp;"yjh0410/CenterNet-Lite"<CenterNet-Lite@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/CenterNet-Lite]  Fix 'Namespace' object has no attribute 'num_classes' (#10)





 
@yjh0410 Are you busy recently?

**Comment by developer0hye** [comment]
@yjh0410 
Oh, sorry...
That's too bad.

I hope you address all trouble. Cheer up!!!

If I live near the your school, I will buy delicious food for you...

Actually I am trying to implement Centernet and make your model better!

**Comment by yjh0410** [comment]
Thanks a lot !


I really like&nbsp;Korean food such as pickle，rice cake，miso soup，seaweed rice and so on.


My CenterNet is too simple and I have no much time and computation power to make it stronger and better which is my regret.


I sincerely wish you can get a better result !






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjh0410/CenterNet-Lite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 晚上9:53
收件人:&nbsp;"yjh0410/CenterNet-Lite"<CenterNet-Lite@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/CenterNet-Lite]  Fix 'Namespace' object has no attribute 'num_classes' (#10)





 
@yjh0410
 Oh, sorry...
 That's too bad.
 
I hope you address all trouble. Cheer up!!!
 
If I live near the your school, I will buy delicious food for you...
 
Actually I am trying to implement Centernet and make your model better!

**Comment by developer0hye** [comment]
I wish someday we will work together!
You are on the PhD courses?

**Comment by yjh0410** [comment]
I wish, too.


Yes, a phD now~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjh0410/CenterNet-Lite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 晚上10:06
收件人:&nbsp;"yjh0410/CenterNet-Lite"<CenterNet-Lite@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/CenterNet-Lite]  Fix 'Namespace' object has no attribute 'num_classes' (#10)





 
I wish someday we will work together!
 You are on the PhD courses?

**Comment by developer0hye** [comment]
@yjh0410 
Great! I believe you will write gorgeous papers!

**Comment by yjh0410** [comment]
Thank you ！Mutual encouragement ！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjh0410/CenterNet-Lite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 晚上10:33
收件人:&nbsp;"yjh0410/CenterNet-Lite"<CenterNet-Lite@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/CenterNet-Lite]  Fix 'Namespace' object has no attribute 'num_classes' (#10)





 
@yjh0410
 Great! I believe you will write gorgeous papers!

**Pull request merged**
